[build]
  base = "frontend"
  publish = "build"
  command = "npm install && REACT_APP_API_URL=$REACT_APP_API_URL craco build"

[build.environment]
  NODE_VERSION = "18"
  NODE_ENV = "production"
  CI = "true"
  REACT_APP_API_URL = "https://rusba-digital-solutions-api.onrender.com/api"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
