[build]
  base = "frontend"
  publish = "build"
  command = "NODE_ENV=production npm install && npm run build"

[build.environment]
  NODE_VERSION = "18"
  NODE_ENV = "production"
  CI = "true"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
