services:
  - type: web
    name: rusba-digital-solutions-api
    env: node
    region: singapore  # Choose the region closest to your users
    runtime: node
    nodeVersion: 18.19.0
    buildCommand: |
      cd server && 
      npm ci --include=dev &&
      npm run build
    startCommand: cd server && npm run start
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: CORS_ORIGIN
        value: https://rusba-digital-solutions.onrender.com  # Update this with your frontend URL
    autoDeploy: true
